// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plan.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Interval int32

const (
	Interval_NotSet Interval = 0
	Interval_Day    Interval = 1
	Interval_Week   Interval = 2
	Interval_Month  Interval = 3
	Interval_Year   Interval = 4
)

var Interval_name = map[int32]string{
	0: "NotSet",
	1: "Day",
	2: "Week",
	3: "Month",
	4: "Year",
}
var Interval_value = map[string]int32{
	"NotSet": 0,
	"Day":    1,
	"Week":   2,
	"Month":  3,
	"Year":   4,
}

func (x Interval) String() string {
	return proto.EnumName(Interval_name, int32(x))
}
func (Interval) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type PlanResponse struct {
	// Types that are valid to be assigned to Responses:
	//	*PlanResponse_Error
	//	*PlanResponse_Success
	Responses isPlanResponse_Responses `protobuf_oneof:"responses"`
}

func (m *PlanResponse) Reset()                    { *m = PlanResponse{} }
func (m *PlanResponse) String() string            { return proto.CompactTextString(m) }
func (*PlanResponse) ProtoMessage()               {}
func (*PlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type isPlanResponse_Responses interface {
	isPlanResponse_Responses()
}

type PlanResponse_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,oneof"`
}
type PlanResponse_Success struct {
	Success *Plan `protobuf:"bytes,2,opt,name=success,oneof"`
}

func (*PlanResponse_Error) isPlanResponse_Responses()   {}
func (*PlanResponse_Success) isPlanResponse_Responses() {}

func (m *PlanResponse) GetResponses() isPlanResponse_Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *PlanResponse) GetError() *Error {
	if x, ok := m.GetResponses().(*PlanResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *PlanResponse) GetSuccess() *Plan {
	if x, ok := m.GetResponses().(*PlanResponse_Success); ok {
		return x.Success
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PlanResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PlanResponse_OneofMarshaler, _PlanResponse_OneofUnmarshaler, _PlanResponse_OneofSizer, []interface{}{
		(*PlanResponse_Error)(nil),
		(*PlanResponse_Success)(nil),
	}
}

func _PlanResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PlanResponse)
	// responses
	switch x := m.Responses.(type) {
	case *PlanResponse_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *PlanResponse_Success:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Success); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PlanResponse.Responses has unexpected type %T", x)
	}
	return nil
}

func _PlanResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PlanResponse)
	switch tag {
	case 1: // responses.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Responses = &PlanResponse_Error{msg}
		return true, err
	case 2: // responses.success
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Plan)
		err := b.DecodeMessage(msg)
		m.Responses = &PlanResponse_Success{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PlanResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PlanResponse)
	// responses
	switch x := m.Responses.(type) {
	case *PlanResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PlanResponse_Success:
		s := proto.Size(x.Success)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Plan struct {
	Id                  string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Amount              uint64            `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Created             int64             `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Currency            Currency          `protobuf:"varint,4,opt,name=currency,enum=Currency" json:"currency,omitempty"`
	Interval            Interval          `protobuf:"varint,5,opt,name=interval,enum=Interval" json:"interval,omitempty"`
	IntervalCount       uint64            `protobuf:"varint,6,opt,name=interval_count,json=intervalCount" json:"interval_count,omitempty"`
	Livemode            bool              `protobuf:"varint,7,opt,name=livemode" json:"livemode,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,8,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name                string            `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	StatementDescriptor string            `protobuf:"bytes,10,opt,name=statement_descriptor,json=statementDescriptor" json:"statement_descriptor,omitempty"`
	TrialPeriodDays     uint64            `protobuf:"varint,11,opt,name=trial_period_days,json=trialPeriodDays" json:"trial_period_days,omitempty"`
}

func (m *Plan) Reset()                    { *m = Plan{} }
func (m *Plan) String() string            { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()               {}
func (*Plan) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Plan) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_UNK
}

func (m *Plan) GetInterval() Interval {
	if m != nil {
		return m.Interval
	}
	return Interval_NotSet
}

func (m *Plan) GetIntervalCount() uint64 {
	if m != nil {
		return m.IntervalCount
	}
	return 0
}

func (m *Plan) GetLivemode() bool {
	if m != nil {
		return m.Livemode
	}
	return false
}

func (m *Plan) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetStatementDescriptor() string {
	if m != nil {
		return m.StatementDescriptor
	}
	return ""
}

func (m *Plan) GetTrialPeriodDays() uint64 {
	if m != nil {
		return m.TrialPeriodDays
	}
	return 0
}

type CreatePlanRequest struct {
	Id                  string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Amount              uint64            `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Currency            Currency          `protobuf:"varint,3,opt,name=currency,enum=Currency" json:"currency,omitempty"`
	Interval            Interval          `protobuf:"varint,4,opt,name=interval,enum=Interval" json:"interval,omitempty"`
	Name                string            `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	IntervalCount       uint64            `protobuf:"varint,6,opt,name=interval_count,json=intervalCount" json:"interval_count,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,7,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatementDescriptor string            `protobuf:"bytes,8,opt,name=statement_descriptor,json=statementDescriptor" json:"statement_descriptor,omitempty"`
	TrialPeriodDays     uint64            `protobuf:"varint,9,opt,name=trial_period_days,json=trialPeriodDays" json:"trial_period_days,omitempty"`
}

func (m *CreatePlanRequest) Reset()                    { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()               {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CreatePlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreatePlanRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreatePlanRequest) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_UNK
}

func (m *CreatePlanRequest) GetInterval() Interval {
	if m != nil {
		return m.Interval
	}
	return Interval_NotSet
}

func (m *CreatePlanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePlanRequest) GetIntervalCount() uint64 {
	if m != nil {
		return m.IntervalCount
	}
	return 0
}

func (m *CreatePlanRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreatePlanRequest) GetStatementDescriptor() string {
	if m != nil {
		return m.StatementDescriptor
	}
	return ""
}

func (m *CreatePlanRequest) GetTrialPeriodDays() uint64 {
	if m != nil {
		return m.TrialPeriodDays
	}
	return 0
}

type GetPlanRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetPlanRequest) Reset()                    { *m = GetPlanRequest{} }
func (m *GetPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPlanRequest) ProtoMessage()               {}
func (*GetPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetPlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePlanRequest struct {
	Id                  string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name                string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	StatementDescriptor string            `protobuf:"bytes,4,opt,name=statement_descriptor,json=statementDescriptor" json:"statement_descriptor,omitempty"`
	TrialPeriodDays     uint64            `protobuf:"varint,5,opt,name=trial_period_days,json=trialPeriodDays" json:"trial_period_days,omitempty"`
}

func (m *UpdatePlanRequest) Reset()                    { *m = UpdatePlanRequest{} }
func (m *UpdatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanRequest) ProtoMessage()               {}
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *UpdatePlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePlanRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *UpdatePlanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePlanRequest) GetStatementDescriptor() string {
	if m != nil {
		return m.StatementDescriptor
	}
	return ""
}

func (m *UpdatePlanRequest) GetTrialPeriodDays() uint64 {
	if m != nil {
		return m.TrialPeriodDays
	}
	return 0
}

type DeletePlanRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeletePlanRequest) Reset()                    { *m = DeletePlanRequest{} }
func (m *DeletePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanRequest) ProtoMessage()               {}
func (*DeletePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *DeletePlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlanSuccess struct {
	Deleted bool   `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeletePlanSuccess) Reset()                    { *m = DeletePlanSuccess{} }
func (m *DeletePlanSuccess) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanSuccess) ProtoMessage()               {}
func (*DeletePlanSuccess) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *DeletePlanSuccess) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DeletePlanSuccess) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlanResponse struct {
	// Types that are valid to be assigned to Responses:
	//	*DeletePlanResponse_Error
	//	*DeletePlanResponse_Success
	Responses isDeletePlanResponse_Responses `protobuf_oneof:"responses"`
}

func (m *DeletePlanResponse) Reset()                    { *m = DeletePlanResponse{} }
func (m *DeletePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanResponse) ProtoMessage()               {}
func (*DeletePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

type isDeletePlanResponse_Responses interface {
	isDeletePlanResponse_Responses()
}

type DeletePlanResponse_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,oneof"`
}
type DeletePlanResponse_Success struct {
	Success *DeletePlanSuccess `protobuf:"bytes,2,opt,name=success,oneof"`
}

func (*DeletePlanResponse_Error) isDeletePlanResponse_Responses()   {}
func (*DeletePlanResponse_Success) isDeletePlanResponse_Responses() {}

func (m *DeletePlanResponse) GetResponses() isDeletePlanResponse_Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *DeletePlanResponse) GetError() *Error {
	if x, ok := m.GetResponses().(*DeletePlanResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *DeletePlanResponse) GetSuccess() *DeletePlanSuccess {
	if x, ok := m.GetResponses().(*DeletePlanResponse_Success); ok {
		return x.Success
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DeletePlanResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DeletePlanResponse_OneofMarshaler, _DeletePlanResponse_OneofUnmarshaler, _DeletePlanResponse_OneofSizer, []interface{}{
		(*DeletePlanResponse_Error)(nil),
		(*DeletePlanResponse_Success)(nil),
	}
}

func _DeletePlanResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DeletePlanResponse)
	// responses
	switch x := m.Responses.(type) {
	case *DeletePlanResponse_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *DeletePlanResponse_Success:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Success); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DeletePlanResponse.Responses has unexpected type %T", x)
	}
	return nil
}

func _DeletePlanResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DeletePlanResponse)
	switch tag {
	case 1: // responses.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Responses = &DeletePlanResponse_Error{msg}
		return true, err
	case 2: // responses.success
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeletePlanSuccess)
		err := b.DecodeMessage(msg)
		m.Responses = &DeletePlanResponse_Success{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DeletePlanResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DeletePlanResponse)
	// responses
	switch x := m.Responses.(type) {
	case *DeletePlanResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DeletePlanResponse_Success:
		s := proto.Size(x.Success)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ListFilter struct {
	Gt  int64 `protobuf:"varint,1,opt,name=gt" json:"gt,omitempty"`
	Gte int64 `protobuf:"varint,2,opt,name=gte" json:"gte,omitempty"`
	Lt  int64 `protobuf:"varint,3,opt,name=lt" json:"lt,omitempty"`
	Lte int64 `protobuf:"varint,4,opt,name=lte" json:"lte,omitempty"`
}

func (m *ListFilter) Reset()                    { *m = ListFilter{} }
func (m *ListFilter) String() string            { return proto.CompactTextString(m) }
func (*ListFilter) ProtoMessage()               {}
func (*ListFilter) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *ListFilter) GetGt() int64 {
	if m != nil {
		return m.Gt
	}
	return 0
}

func (m *ListFilter) GetGte() int64 {
	if m != nil {
		return m.Gte
	}
	return 0
}

func (m *ListFilter) GetLt() int64 {
	if m != nil {
		return m.Lt
	}
	return 0
}

func (m *ListFilter) GetLte() int64 {
	if m != nil {
		return m.Lte
	}
	return 0
}

type ListPlansRequest struct {
	Created       *ListFilter `protobuf:"bytes,1,opt,name=created" json:"created,omitempty"`
	EndingBefore  string      `protobuf:"bytes,2,opt,name=ending_before,json=endingBefore" json:"ending_before,omitempty"`
	StartingAfter string      `protobuf:"bytes,3,opt,name=starting_after,json=startingAfter" json:"starting_after,omitempty"`
	Limit         int32       `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListPlansRequest) Reset()                    { *m = ListPlansRequest{} }
func (m *ListPlansRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPlansRequest) ProtoMessage()               {}
func (*ListPlansRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *ListPlansRequest) GetCreated() *ListFilter {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *ListPlansRequest) GetEndingBefore() string {
	if m != nil {
		return m.EndingBefore
	}
	return ""
}

func (m *ListPlansRequest) GetStartingAfter() string {
	if m != nil {
		return m.StartingAfter
	}
	return ""
}

func (m *ListPlansRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*PlanResponse)(nil), "PlanResponse")
	proto.RegisterType((*Plan)(nil), "Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "CreatePlanRequest")
	proto.RegisterType((*GetPlanRequest)(nil), "GetPlanRequest")
	proto.RegisterType((*UpdatePlanRequest)(nil), "UpdatePlanRequest")
	proto.RegisterType((*DeletePlanRequest)(nil), "DeletePlanRequest")
	proto.RegisterType((*DeletePlanSuccess)(nil), "DeletePlanSuccess")
	proto.RegisterType((*DeletePlanResponse)(nil), "DeletePlanResponse")
	proto.RegisterType((*ListFilter)(nil), "ListFilter")
	proto.RegisterType((*ListPlansRequest)(nil), "ListPlansRequest")
	proto.RegisterEnum("Interval", Interval_name, Interval_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Plans service

type PlansClient interface {
	UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...grpc.CallOption) (*DeletePlanResponse, error)
	GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (Plans_ListPlansClient, error)
}

type plansClient struct {
	cc *grpc.ClientConn
}

func NewPlansClient(cc *grpc.ClientConn) PlansClient {
	return &plansClient{cc}
}

func (c *plansClient) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := grpc.Invoke(ctx, "/Plans/UpdatePlan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := grpc.Invoke(ctx, "/Plans/CreatePlan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansClient) DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...grpc.CallOption) (*DeletePlanResponse, error) {
	out := new(DeletePlanResponse)
	err := grpc.Invoke(ctx, "/Plans/DeletePlan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansClient) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := grpc.Invoke(ctx, "/Plans/GetPlan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansClient) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (Plans_ListPlansClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Plans_serviceDesc.Streams[0], c.cc, "/Plans/ListPlans", opts...)
	if err != nil {
		return nil, err
	}
	x := &plansListPlansClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Plans_ListPlansClient interface {
	Recv() (*PlanResponse, error)
	grpc.ClientStream
}

type plansListPlansClient struct {
	grpc.ClientStream
}

func (x *plansListPlansClient) Recv() (*PlanResponse, error) {
	m := new(PlanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Plans service

type PlansServer interface {
	UpdatePlan(context.Context, *UpdatePlanRequest) (*PlanResponse, error)
	CreatePlan(context.Context, *CreatePlanRequest) (*PlanResponse, error)
	DeletePlan(context.Context, *DeletePlanRequest) (*DeletePlanResponse, error)
	GetPlan(context.Context, *GetPlanRequest) (*PlanResponse, error)
	ListPlans(*ListPlansRequest, Plans_ListPlansServer) error
}

func RegisterPlansServer(s *grpc.Server, srv PlansServer) {
	s.RegisterService(&_Plans_serviceDesc, srv)
}

func _Plans_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plans/UpdatePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServer).UpdatePlan(ctx, req.(*UpdatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plans_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plans/CreatePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plans_DeletePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServer).DeletePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plans/DeletePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServer).DeletePlan(ctx, req.(*DeletePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plans_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plans/GetPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServer).GetPlan(ctx, req.(*GetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plans_ListPlans_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPlansRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlansServer).ListPlans(m, &plansListPlansServer{stream})
}

type Plans_ListPlansServer interface {
	Send(*PlanResponse) error
	grpc.ServerStream
}

type plansListPlansServer struct {
	grpc.ServerStream
}

func (x *plansListPlansServer) Send(m *PlanResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Plans_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Plans",
	HandlerType: (*PlansServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePlan",
			Handler:    _Plans_UpdatePlan_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _Plans_CreatePlan_Handler,
		},
		{
			MethodName: "DeletePlan",
			Handler:    _Plans_DeletePlan_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _Plans_GetPlan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPlans",
			Handler:       _Plans_ListPlans_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plan.proto",
}

func init() { proto.RegisterFile("plan.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0xeb, 0x44,
	0x14, 0x8d, 0xbf, 0x12, 0xfb, 0xe6, 0x25, 0xcf, 0x99, 0x3e, 0x21, 0x2b, 0x0b, 0x14, 0xfc, 0x54,
	0x29, 0x2a, 0x92, 0xa1, 0x61, 0x01, 0xe2, 0x4b, 0xa2, 0x4d, 0xa1, 0x48, 0x14, 0x55, 0x53, 0x21,
	0xc4, 0x86, 0x68, 0x1a, 0xdf, 0x06, 0xab, 0x8e, 0x9d, 0x8e, 0x27, 0x95, 0xf2, 0x07, 0xd8, 0xb3,
	0x46, 0xe2, 0x87, 0xf0, 0xeb, 0xd0, 0x8c, 0x3f, 0xe2, 0xd6, 0xa4, 0x4d, 0x17, 0xdd, 0xcd, 0x3d,
	0x73, 0xef, 0xcc, 0x9d, 0x73, 0xae, 0x8f, 0x0c, 0xb0, 0x8a, 0x59, 0x12, 0xac, 0x78, 0x2a, 0xd2,
	0xa1, 0x3b, 0x5f, 0x73, 0x8e, 0xc9, 0x3c, 0xc2, 0xac, 0x40, 0xba, 0xc8, 0x79, 0xca, 0xf3, 0xc0,
	0xff, 0x1d, 0xde, 0x5c, 0xc6, 0x2c, 0xa1, 0x98, 0xad, 0xd2, 0x24, 0x43, 0xf2, 0x21, 0x58, 0x6a,
	0xdb, 0xd3, 0x46, 0xda, 0xb8, 0x3b, 0x69, 0x07, 0x67, 0x32, 0x3a, 0x6f, 0xd1, 0x1c, 0x26, 0x1f,
	0x41, 0x27, 0x5b, 0xcf, 0xe7, 0x98, 0x65, 0x9e, 0xae, 0x32, 0xac, 0x40, 0xd6, 0x9f, 0xb7, 0x68,
	0x89, 0x9f, 0x74, 0xc1, 0xe1, 0xc5, 0x71, 0x99, 0xff, 0xaf, 0x01, 0xa6, 0x4c, 0x20, 0x7d, 0xd0,
	0xa3, 0x50, 0x9d, 0xea, 0x50, 0x3d, 0x0a, 0xc9, 0x07, 0xd0, 0x66, 0xcb, 0x74, 0x9d, 0x08, 0x75,
	0x8e, 0x49, 0x8b, 0x88, 0x78, 0xd0, 0x99, 0x73, 0x64, 0x02, 0x43, 0xcf, 0x18, 0x69, 0x63, 0x83,
	0x96, 0x21, 0x39, 0x04, 0xbb, 0x78, 0xcb, 0xc6, 0x33, 0x47, 0xda, 0xb8, 0x3f, 0x71, 0x82, 0xd3,
	0x02, 0xa0, 0xd5, 0x96, 0x4c, 0x8b, 0x12, 0x81, 0xfc, 0x9e, 0xc5, 0x9e, 0x55, 0xa4, 0xfd, 0x58,
	0x00, 0xb4, 0xda, 0x22, 0x87, 0xd0, 0x2f, 0xd7, 0xb3, 0xb9, 0xea, 0xa3, 0xad, 0xfa, 0xe8, 0x95,
	0xe8, 0xa9, 0x6a, 0x67, 0x08, 0x76, 0x1c, 0xdd, 0xe3, 0x32, 0x0d, 0xd1, 0xeb, 0x8c, 0xb4, 0xb1,
	0x4d, 0xab, 0x98, 0x7c, 0x02, 0xf6, 0x12, 0x05, 0x0b, 0x99, 0x60, 0x9e, 0x3d, 0x32, 0xc6, 0xdd,
	0xc9, 0x81, 0x22, 0x23, 0xb8, 0x28, 0xd0, 0xb3, 0x44, 0xf0, 0x0d, 0xad, 0x92, 0x08, 0x01, 0x33,
	0x61, 0x4b, 0xf4, 0x1c, 0xc5, 0x82, 0x5a, 0x93, 0x63, 0x78, 0x97, 0x09, 0x26, 0x70, 0x89, 0x89,
	0x98, 0x85, 0x98, 0xcd, 0x79, 0xb4, 0x12, 0x29, 0xf7, 0x40, 0xe5, 0x1c, 0x54, 0x7b, 0xd3, 0x6a,
	0x8b, 0x1c, 0xc1, 0x40, 0xf0, 0x88, 0xc5, 0xb3, 0x15, 0xf2, 0x28, 0x0d, 0x67, 0x21, 0xdb, 0x64,
	0x5e, 0x57, 0x75, 0xff, 0x56, 0x6d, 0x5c, 0x2a, 0x7c, 0xca, 0x36, 0xd9, 0xf0, 0x2b, 0xe8, 0x3d,
	0xe8, 0x86, 0xb8, 0x60, 0xdc, 0xe2, 0xa6, 0x10, 0x42, 0x2e, 0xc9, 0x3b, 0xb0, 0xee, 0x59, 0xbc,
	0x46, 0x25, 0x84, 0x43, 0xf3, 0xe0, 0x4b, 0xfd, 0x0b, 0xcd, 0xff, 0xc7, 0x80, 0xc1, 0xa9, 0x62,
	0x3f, 0x9f, 0x91, 0xbb, 0x35, 0x66, 0x62, 0x6f, 0x25, 0xeb, 0x7a, 0x19, 0xfb, 0xe9, 0x65, 0xee,
	0xd6, 0xab, 0xe4, 0xce, 0xaa, 0x71, 0xb7, 0xa7, 0x86, 0x5f, 0xd7, 0x74, 0xea, 0x28, 0x9d, 0x46,
	0x41, 0xe3, 0x59, 0x3b, 0x45, 0xdb, 0x25, 0x90, 0xfd, 0x42, 0x81, 0x9c, 0x57, 0x10, 0x68, 0x04,
	0xfd, 0x1f, 0x50, 0x3c, 0x21, 0x8e, 0xff, 0x97, 0x0e, 0x83, 0x5f, 0x56, 0xe1, 0x33, 0x12, 0xd6,
	0x19, 0xd2, 0x0b, 0x86, 0x1a, 0x55, 0xcf, 0x8e, 0xb5, 0xb1, 0xc7, 0x58, 0x9b, 0x2f, 0x64, 0xcd,
	0x7a, 0x05, 0xd6, 0xde, 0xc3, 0x60, 0x8a, 0x31, 0x3e, 0x49, 0x89, 0xff, 0x4d, 0x3d, 0xe9, 0x2a,
	0xb7, 0x36, 0x69, 0x4e, 0xa1, 0x02, 0xf3, 0x4c, 0x9b, 0x96, 0x61, 0x51, 0xae, 0x57, 0xe5, 0x77,
	0x40, 0xea, 0x77, 0xec, 0xe9, 0xae, 0xc1, 0x63, 0x77, 0x25, 0x41, 0xa3, 0x89, 0x9d, 0x56, 0x7b,
	0x09, 0xf0, 0x53, 0x94, 0x89, 0xef, 0xa3, 0x58, 0x20, 0x97, 0x0d, 0x2d, 0x84, 0xba, 0xc7, 0xa0,
	0xfa, 0x42, 0x48, 0x82, 0x16, 0x22, 0x27, 0xc3, 0xa0, 0x72, 0x29, 0x33, 0x62, 0x51, 0x98, 0xac,
	0x1e, 0xab, 0x8c, 0x58, 0xa0, 0x52, 0xc8, 0xa0, 0x72, 0xe9, 0xff, 0xad, 0x81, 0x2b, 0x8f, 0x94,
	0xb7, 0x67, 0x25, 0x51, 0x87, 0x5b, 0x83, 0xce, 0x5f, 0xd1, 0x0d, 0xb6, 0xd7, 0x6e, 0xdd, 0xfa,
	0x3d, 0xf4, 0x30, 0x09, 0xa3, 0x64, 0x31, 0xbb, 0xc6, 0x9b, 0x94, 0x97, 0x32, 0xbc, 0xc9, 0xc1,
	0x13, 0x85, 0xc9, 0x0f, 0x38, 0x13, 0x8c, 0x0b, 0x99, 0xc6, 0x6e, 0x04, 0xf2, 0x62, 0x86, 0x7a,
	0x25, 0xfa, 0x9d, 0x04, 0xa5, 0x94, 0x71, 0xb4, 0x8c, 0x84, 0xea, 0xcd, 0xa2, 0x79, 0x70, 0xf4,
	0x2d, 0xd8, 0xa5, 0x4f, 0x10, 0x80, 0xf6, 0xcf, 0xa9, 0xb8, 0x42, 0xe1, 0xb6, 0x48, 0x07, 0x8c,
	0x29, 0xdb, 0xb8, 0x1a, 0xb1, 0xc1, 0xfc, 0x15, 0xf1, 0xd6, 0xd5, 0x89, 0x03, 0xd6, 0x45, 0x9a,
	0x88, 0x3f, 0x5c, 0x43, 0x82, 0xbf, 0x21, 0xe3, 0xae, 0x39, 0xf9, 0x53, 0x07, 0x4b, 0xbd, 0x8c,
	0x1c, 0x03, 0x6c, 0xa7, 0x9d, 0x90, 0xe6, 0xe8, 0x0f, 0x7b, 0x41, 0x5d, 0x47, 0xbf, 0x25, 0x4b,
	0xb6, 0x16, 0x42, 0x48, 0xd3, 0x4f, 0x9a, 0x25, 0x9f, 0x03, 0x6c, 0xc5, 0x24, 0x75, 0x65, 0xcb,
	0x92, 0x83, 0xa0, 0x39, 0x33, 0x7e, 0x8b, 0x7c, 0x0c, 0x9d, 0xe2, 0x2b, 0x27, 0x6f, 0x83, 0x87,
	0xdf, 0xfb, 0xff, 0x35, 0xe6, 0x54, 0x92, 0x91, 0x41, 0xf0, 0x58, 0xbe, 0x46, 0xc1, 0xa7, 0xda,
	0x75, 0x5b, 0xfd, 0x0a, 0x7c, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xa0, 0xf9, 0x7d,
	0x37, 0x08, 0x00, 0x00,
}
